### ISSUE TITLE
웹 페이지 하단 이동 버튼 동작 안하는 현상

### ISSUE THREAD

**Issue by ljhyeok** [danmin20/LeeJeongMin#6]
[velog 글](https://velog.io/@danmin20/%EC%83%81%ED%83%9C%EA%B4%80%EB%A6%AC-%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC-%EB%AD%98-%EC%93%B8%EA%B9%8C)을 보다가 우연히 들르게 됐습니다!  

정민님 웹 사이트 들어가 봤는데, 인터랙션이나 디자인 엄청 심혈을 기우려서 만든게 느껴지더라구요!
대단합니당

그러다가 우연히 발견한 버그인데....
웹 페이지 하단으로 이동하는 스크롤 버튼이 동작을 안하더라구요 ㅎㅎ;

<img width="1436" alt="스크린샷 2021-09-23 오전 11 59 14" src="https://user-images.githubusercontent.com/49031190/134450574-e0ef06df-b0f6-4b3b-8637-824e55dbb2e1.png">

`react-lottie` 라이브러리에서 `onClick` 이벤트 리스너를 props를 받는지는 모르겠어서....
div로 한번 감싸서 onClick 이벤트 리스너 등록해도 될것 같긴 합니다!

```js
          <div onClick={() => window.scrollTo(0, document.body.scrollHeight)}>
            <Lottie
              options={lottieOptions}
              ariaRole="img"
              isClickToPauseDisabled
            />
          </div>
```

**Comment by danmin20** [comment]
저건 버튼이 아니라 스크롤 표시로 넣어둔 겁니다ㅎㅎ
감사합니다 이슈 닫도록 할게요~
